use HOSPITAL;
#DETAILS OF PATIENTS TREATED BY DAINTON FOSTER
SELECT P.* FROM PATIENTS AS P,DOCTOR AS D WHERE P.DOC_ID=D.STAFF_ID AND D.DOC_NAME="Dainton Foster";
#COUNT OF STAFF IN EACH OCCUPATION
SELECT COUNT(*) AS COUNT,OCCUPATION FROM STAFF GROUP BY OCCUPATION;
#DETAILS OF STAFF WORKING IN GLOBAL HOSPITAL GROUP
SELECT S.* FROM STAFF AS S, BRANCH AS B WHERE S.BRANCH_ID=B.BRANCH_ID AND B.BRANCH_NAME="Global Hospitals Group";
#DETAILS OF PATIENTS WHO BOUGHT CLINDA
SELECT P.* FROM PATIENTS AS P,MEDICINE AS M WHERE P.PATIENT_ID=M.REFFERED_TO AND M.MEDNAME="Clinda";
#HOSPITAL WISE COUNT OF PATIENTS
SELECT COUNT(*) AS NUMBER_OF_PATIENTS,BRANCH_NAME FROM PATIENTS AS P,BRANCH AS B WHERE P.BRANCH_ID=B.BRANCH_ID GROUP BY BRANCH_NAME;
#DETAILS OF PATIENTS ABOVE THE AGE OF 30
SELECT * FROM PATIENTS WHERE AGE>30;
#OCCUPATION WISE SALARY OF STAFF
SELECT AVG(SALARY),OCCUPATION FROM STAFF GROUP BY OCCUPATION;
#PATIENT WHOSE REPORTS WERE GENERATED ON 2023-02-05
SELECT P.* FROM PATIENTS AS P,TESTS AS T WHERE P.PATIENT_ID=T.REFFERED_TO AND T.REPORT_DATE='2023-02-05';